FROM node:8 as build
WORKDIR /build
COPY . .
RUN npm install
RUN npm run build

FROM node:12-alpine as serve
WORKDIR /opt/app
ARG PORT=80
ENV PORT $PORT
COPY package.json package-lock.json* .env* ./
COPY --from=build /build/dist /opt/app/dist
RUN apk add g++ make python
RUN npm install --only=production
EXPOSE $PORT
CMD ["node", "dist/src/app.js"]