defaults: &defaults
  working_directory: ~/user-service
  docker:
    - image: cyber4all/circleci-aws:docker-git
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image & Unit Test
          command: | 
            docker build -t user-service:$CIRCLE_SHA1 . --build-arg UNIT_TEST=1 --build-arg CLARK_DB_URI_TEST=$CLARK_DB_URI_TEST
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Publish Image 
          command: |
            docker tag user-service:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/user-service:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/user-service:${CIRCLE_SHA1}"
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./package.json
              - ./deploy.sh

  integration-test:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/user-service
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/user-service:${CIRCLE_SHA1}"
      - run:
          name: Run Integration Test
          command: |
            echo docker run -it user-service:$CIRCLE_SHA1 npm test

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/user-service
      - setup_remote_docker
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/user-service:${CIRCLE_SHA1}"
      - run:
          name: Publish Image 
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/user-service:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/user-service:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/user-service:${SEMVER}"
      - run:
          name: Deploy to ECS
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            export DOCKER_IMAGE="${DOCKER_USER_ORG}/user-service:${SEMVER}"
            chmod +x ./deploy.sh
            sh ./deploy.sh
            
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              ignore: /master/
      - integration-test:
          requires:
            - build
          context:
            - DockerHub
          filters:
            branches:
              ignore: /master/

  build-test-and-deploy-production:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              only: /master/
      - integration-test:
          requires:
            - build
          context:
            - DockerHub
          filters:
            branches:
              only: /master/
      - deploy-production:
          requires:
            - integration-test
          context:
            - DockerHub
          filters:
            branches:
              only: /master/